name: diabe_trek
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  camera: ^0.10.0+3
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.2
  gap: ^2.0.0
  http: ^0.13.5
  image_picker: ^0.8.4+11
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
